[package]

name = "leveldb"
version = "0.9.0"
authors = [ "Florian Gilcher <florian.gilcher@asquera.de>" ]

description = "An interface for leveldb"

license = "MIT"
readme = "README.md"

documentation = "http://skade.github.io/leveldb/"
homepage = "https://github.com/skade/leveldb"
repository = "https://github.com/skade/leveldb"

[lib]

name = "leveldb"

[dependencies]
libc = "0.2"

[dependencies.leveldb-sys]
version="3.0"
path="../leveldb-sys"

[dev-dependencies]
tempdir = "0.3"

[[test]]
name = "tests"
