[package]
name = "timestamping"
version = "0.1.0"
authors = ["Aleksei Sidorov <aleksei.sidorov@xdev.re>"]

[dependencies]
clap = "2.22.0"
env_logger = "0.4.0"

params = "0.6.0"
router = "0.5.1"
iron = "0.5.1"

chrono = "0.3.0"
rand = "0.3.0"
log = "0.3.0"
byteorder = "1.0.0"
bitcoin = "0.9.1"

serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"

exonum = "0.1.0"
exonum-configuration = "0.1.0"
exonum-btc-anchoring = "0.1.0"
