[package]
name = "exonum-configuration"
version = "0.9.0"
authors = ["The Exonum Team <exonum@bitfury.com>"]
homepage = "https://exonum.com/doc/advanced/configuration-updater/"
repository = "https://github.com/exonum/exonum"
documentation = "https://docs.rs/exonum-configuration"
readme = "README.md"
license = "Apache-2.0"
keywords = ["exonum", "blockchain", "config", "configuration"]
categories = ["database-implementations", "config"]
description = "An Exonum service that provides functionality of modifying the global configuration."

[badges]
travis-ci = { repository = "exonum/exonum" }
circle-ci = { repository = "exonum/exonum" }

[dependencies]
clap = "2.30.0"
env_logger = "=0.5.10"
exonum = { version = "0.9.0", path = "../../exonum" }
failure = "=0.1.1"
lazy_static = "1.0.0"
log = "=0.4.3"
serde = "1.0.10"
serde_derive = "1.0.10"
tempdir = "=0.3.7"

[dev-dependencies]
exonum-testkit = { version = "0.9.0", path = "../../testkit" }
pretty_assertions = "=0.5.1"
assert_matches = "1.2.0"
