[package]
name = "sandbox_tests"
version = "0.1.0"
authors = ["Ivan Ivashchenko <ivan.ivashchenko@xdev.re",
           "Aleksey Sidorov <aleksei.sidorov@xdev.re>"]

[dependencies]
exonum = {version="0.1", path="../../../exonum"}
sandbox = {version="0.1", path="../../../sandbox"}
blockchain_explorer = {version="0.1", path="../../../blockchain_explorer"}
configuration_service = {version="0.1.0", path="../"}
serde = "0.8.23"
serde_json = "0.8.6"
serde_derive = "0.8.0"
log = "0.3"
