[package]
name = "exonum-soak-tests"
version = "0.0.0"
edition = "2018"
authors = ["The Exonum Team <contact@exonum.com>"]
homepage = "https://exonum.com/"
repository = "https://github.com/exonum/exonum"
readme = "README.md"
description = "The crate for soak testing of Exonum node."
publish = false

[dependencies]
exonum = { version = "1.0.0-rc.3", path = "../../exonum" }
exonum-derive = { version = "1.0.0-rc.3", path = "../../components/derive" }
exonum-merkledb = { version = "1.0.0-rc.3", path = "../../components/merkledb" }
exonum-node = { version = "1.0.0-rc.3", path = "../../exonum-node" }
exonum-rust-runtime = { version = "1.0.0-rc.3", path = "../../runtimes/rust" }

anyhow = "1.0.26"
bincode = "1.2.1"
futures = "0.3.4"
log = "0.4.6"
reqwest = { version = "0.10.2", features = ["json"] }
serde = "1.0"
serde_derive = "1.0"
structopt = "0.3.9"

[dependencies.tokio]
version = "0.2.13"
features = ["blocking", "dns", "io-util", "macros", "rt-threaded", "tcp", "time"]
