[package]
name = "exonum-sample-runtime"
version = "0.0.0"
authors = ["The Exonum Team <contact@exonum.com>"]
edition = "2018"
homepage = "https://exonum.com/"
repository = "https://github.com/exonum/exonum"
license = "Apache-2.0"
keywords = ["exonum", "blockchain", "example"]
categories = ["rust-patterns"]
description = "Minimal Exonum blockchain example implementing a simple runtime."
publish = false

[dependencies]
exonum = { version = "1.0.0-rc.3", path = "../../exonum" }
exonum-derive = { version = "1.0.0-rc.3", path = "../../components/derive" }
exonum-merkledb = { version = "1.0.0-rc.3", path = "../../components/merkledb" }
exonum-node = { version = "1.0.0-rc.3", path = "../../exonum-node" }
exonum-supervisor = { version = "1.0.0-rc.3", path = "../../services/supervisor" }
exonum-rust-runtime = { version = "1.0.0-rc.3", path = "../../runtimes/rust" }

futures = "0.3.4"

[dependencies.tokio]
version = "0.2.13"
features = ["blocking", "dns", "io-util", "macros", "rt-threaded", "tcp", "time"]
