[package]
name = "exonum-sample-runtime"
version = "0.13.0-rc.2"
authors = ["The Exonum Team <contact@exonum.com>"]
edition = "2018"
homepage = "https://exonum.com/"
repository = "https://github.com/exonum/exonum"
license = "Apache-2.0"
keywords = ["exonum", "blockchain", "example"]
categories = ["rust-patterns"]
description = "Minimal Exonum blockchain example implementing a simple runtime."

[dependencies]
futures = "0.1.25"

exonum = { version = "0.13.0-rc.2", path = "../../exonum" }
exonum-derive = { version = "0.13.0-rc.2", path = "../../components/derive" }
exonum-merkledb = { version = "0.13.0-rc.2", path = "../../components/merkledb" }
exonum-supervisor = { version = "0.13.0-rc.2", path = "../../services/supervisor" }
exonum-rust-runtime = { version = "0.13.0-rc.2", path = "../../runtimes/rust" }
