[package]
name = "exonum-rust-runtime-proto-tests"
version = "0.0.0"
edition = "2018"
authors = ["The Exonum Team <contact@exonum.com>"]
homepage = "https://exonum.com/"
repository = "https://github.com/exonum/exonum"
readme = "README.md"
description = "The test crate for testing rust runtime API endpoints."
publish = false

[dependencies]
exonum = { version = "1.0.0", path = "../../exonum" }
exonum-derive = { version = "1.0.0", path = "../../components/derive" }
exonum-merkledb = { version = "1.0.0", path = "../../components/merkledb" }
exonum-proto = { version = "1.0.0", path = "../../components/proto" }
exonum-rust-runtime = { version = "1.0.0", path = "../../runtimes/rust" }
exonum-testkit = { version = "1.0.0", path = "../../test-suite/testkit" }

anyhow = "1.0"
bit-vec = "0.6"
protobuf = "3"
pretty_assertions = "1"
serde = "1.0"
serde_derive = "1.0"
time = { version = "0.3", features = [ "macros", "serde" ] }

[dev-dependencies]
exonum-api = { version = "1.0.0", path = "../../components/api" }
reqwest = "0.11"

[dev-dependencies.tokio]
version = "1"
features = ["io-util", "macros", "rt-multi-thread", "net", "time"]

[build-dependencies]
exonum-build = { version = "1.0.1", path = "../../components/build" }
