[package]
name = "exonum-node-tests"
version = "0.13.0-rc.2"
edition = "2018"
authors = ["The Exonum Team <contact@exonum.com>"]
license = "Apache-2.0"
description = "A collection of tests of the Exonum node."
publish = false

[dependencies]
exonum = { version = "0.13.0-rc.2", path = "../../exonum" }
exonum-derive = { version = "0.13.0-rc.2", path = "../../components/derive" }
futures = "0.1.25"
tokio = "0.1.14"
tokio-core = "0.1.17"
