[package]
name = "exonum-middleware-service"
version = "1.0.0"
edition = "2018"
authors = ["The Exonum Team <contact@exonum.com>"]
homepage = "https://exonum.com/"
repository = "https://github.com/exonum/exonum"
documentation = "https://docs.rs/exonum-middleware-service"
readme = "README.md"
license = "Apache-2.0"
keywords = ["exonum", "batch", "versioning"]
categories = ["cryptography"]
description = "Composability utilities for Exonum, packaged as a service"

[badges]
travis-ci = { repository = "exonum/exonum" }

[dependencies]
exonum = { version = "1.0.0", path = "../../exonum" }
exonum-derive = { version = "1.0.0", path = "../../components/derive" }
exonum-merkledb = { version = "1.0.0", path = "../../components/merkledb" }
exonum-proto = { version = "1.0.0", path = "../../components/proto" }
exonum-rust-runtime = { version = "1.0.0", path = "../../runtimes/rust" }

anyhow = "1.0"
protobuf = "2.17.0"
semver = { version = "0.11.0", features = ["serde"] }
serde = "1.0"
serde_derive = "1.0"

[dev-dependencies]
exonum-testkit = { version = "1.0.0", path = "../../test-suite/testkit" }
serde_json = "1.0"

[build-dependencies]
exonum-build = { version = "1.0.1", path = "../../components/build" }
